In [2]:
import numpy as np

In [4]:
"Create a 1D NumPy array of the first 10 even numbers."
a=np.array([2,4,6,8,10,12,14,16,18,20])
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
"Create a 3x3 matrix with values ranging from 0 to 8"
a=np.matrix([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
"What is the shape, size, and dtype of the above matrix?"
print(a.shape)
print(np.size(a))
print(a.dtype)

(3, 3)
9
int32


In [11]:
"Create a 5x5 array filled with the value 7."
a=np.full((5,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [15]:
"Create an identity matrix of size 4."
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
"Reverse a 1D array without using [::-1]"
a = np.array([1,2,3,4,5])
a = np.flip(a)
print(a)

[5 4 3 2 1]


In [26]:
"Create a 3D array (2x3x4) filled with random integers from 10 to 99"
a=np.random.randint(10,99,24)
b=a.reshape(2,3,4)
print(b)

[[[24 85 75 80]
  [93 77 67 90]
  [71 73 18 82]]

 [[20 81 79 65]
  [62 52 32 10]
  [74 14 95 89]]]


In [43]:
"Replace all odd numbers in an array with -1 (in-place)"
a=np.array([1,2,3,4,5,6,7,8,9])
a[a%2!=0]=-1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1]


In [45]:
"Flatten a multi-dimensional array into 1D."
a=np.array([[[1,2,3],[4,5,6]]])
b=a.flatten()
print(b)

[1 2 3 4 5 6]


In [49]:
"Get the indices of non-zero elements from the array [1, 0, 2, 0, 3, 0, 4]"
a=np.array([1, 0, 2, 0, 3, 0, 4])
b=np.where(a!=0)
print(b)

(array([0, 2, 4, 6], dtype=int64),)


In [52]:
"Create two arrays a and b of shape (3,) with values [2, 4, 6] and [1, 3, 5] respectively. Perform element-wise addition, subtraction, multiplication, and division"
a=np.array([2,4,6])
b=np.array([1,3,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


In [54]:
"Given an array a = np.array([1, 4, 9, 16, 25]), compute the square root of each element"
a = np.array([1, 4, 9, 16, 25])
print(np.sqrt(a))

[1. 2. 3. 4. 5.]


In [57]:
"Apply the sine and cosine functions to the array np.array([0, π/2, π])"
a=np.array([0, np.pi/2, np.pi])
print(np.sin(a))
print(np.cos(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [60]:
"Use NumPy to generate an array of 10 random floats between 0 and 1. Clip the values between 0.3 and 0.7."
a=np.random.rand(10)
b=np.clip(a,0.3,0.7) 
print(b)

[0.7        0.7        0.7        0.38487595 0.49045313 0.7
 0.7        0.3        0.51147308 0.45361163]


In [63]:
"Create an array [5.3, 2.8, 9.6] and apply np.floor, np.ceil, and np.round"
a=np.array([5.3, 2.8, 9.6])
print(np.floor(a))
print(np.ceil(a))
print(np.round(a))

[5. 2. 9.]
[ 6.  3. 10.]
[ 5.  3. 10.]


In [68]:
"Create a 2D array a of shape (3,3) filled with values 1 to 9. Calculate the sum, mean, and standard deviation of the entire array."
a=np.array([1,2,3,4,5,6,7,8,9])
a=a.reshape(3,3)
print(np.sum(a))
print(np.mean(a))
print(np.std(a))

45
5.0
2.581988897471611


In [71]:
"Using the same array from Q6, calculate the sum along: Rows (axis=1) and Columns (axis=0)"
a=np.array([1,2,3,4,5,6,7,8,9])
a=a.reshape(3,3)
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

[ 6 15 24]
[12 15 18]


In [76]:
"Given an array a = np.array([10, 20, 30, 40, 50]), find the index of the minimum and maximum values."
a = np.array([10, 20, 30, 40, 50])
b=np.where(a==np.min(a))
print(b)
c=np.where(a==np.max(a))
print(c)

(array([0], dtype=int64),)
(array([4], dtype=int64),)


In [78]:
"Given an array a = np.array([10, 15, 20, 25, 30]), filter and print only the values greater than 20."
a = np.array([10, 15, 20, 25, 30])
print(a[a>20])

[25 30]


In [89]:
"Create an array of 6 random integers between 0 and 10. Replace all values less than 5 with 0 (in-place)"
a=np.random.randint(0,10,6)
a[a<5]=0
print(a)

[0 0 7 7 0 5]


In [93]:
"Create a 3x3 array with values from 1 to 9. Add 5 to every element using broadcasting"
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
c=np.array([5])
print(b+c)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [118]:
"Given a 3x3 array, subtract the mean of each column from the respective column using broadcasting"
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
b=np.mean(a,axis=0).reshape(1,3)
print(np.subtract(a,b))

[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [120]:
"Create a 3x3 array. Replace all values greater than 5 with 100 using boolean indexing"
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a[a>5]=100
print(a)

[[  1   2   3]
 [  4   5 100]
 [100 100 100]]


In [125]:
"Given an array a = np.array([10, 20, 30, 40, 50]), extract the elements at positions 0, 2, and 4 using fancy indexing."
a = np.array([10, 20, 30, 40, 50])
#simple indexing
print(a[0],a[2],a[4]) 
#fancy indexing
b=[0,2,4] 
print(a[b])

10 30 50
[10 30 50]


In [127]:
'Using the same array from Q4, set the elements at index positions [1, 3] to -99 using fancy indexing.'
a = np.array([10, 20, 30, 40, 50])
b=[1,3]
a[b]=-99
print(a)

[ 10 -99  30 -99  50]


In [134]:
'Create a 4x4 array filled with values from 0 to 15. Extract the diagonal elements using indexing'
a=np.arange(0,16).reshape(4,4)
print(np.diag(a))

[ 0  5 10 15]


In [147]:
'Given a 2D array of shape (5,5), extract all the elements in the second row and third column'
a=np.arange(25).reshape(5,5)
print(a[1,0:5])
print(a[0:5,2])

[5 6 7 8 9]
[ 2  7 12 17 22]


In [150]:
'Explain with code: difference between .copy() and just assigning an array slice. Show that modifying a slice also modifies the original array unless .copy() is used.'
a=np.array([1,2,3])
b=a.copy()
b[1]=20
print(a)
print(b)

[1 2 3]
[ 1 20  3]


In [158]:
'Use advanced indexing to extract elements at positions (0,0), (1,1), (2,2), (3,3) from a 2D 4x4 array of values from 0 to 15.'
a=np.arange(0,16).reshape(4,4)
print(np.diag(a))
#or
print(a[[0,1,2,3], [0,1,2,3]])


[ 0  5 10 15]
[ 0  5 10 15]


In [159]:
'Create a 1D array of length 10 and set all even-indexed positions to 1 and all odd-indexed positions to -1 using slicing.'
a=np.arange(10)
a[::2]=1
a[1::2]=-1
print(a)

[ 1 -1  1 -1  1 -1  1 -1  1 -1]


In [164]:
'Given a = np.array([20, 10, 40, 30]), sort the array in ascending order and return both: The sorted array and The original indices that would sort the array (argsort)'
a = np.array([20, 10, 40, 30])
print(np.sort(a))
print(np.argsort(a))

[10 20 30 40]
[1 0 3 2]


In [166]:
'Given a = np.array([5, 10, 15, 20, 25]), use np.where to: Replace values less than 15 with 0 and Keep values >= 15 unchanged'
a = np.array([5, 10, 15, 20, 25])
a[np.where(a<15)]=0
print(a)


[ 0  0 15 20 25]


In [171]:
'Given an array a = np.array([1, 2, 2, 3, 4, 4, 4, 5]), find: All unique elements and The count of each unique element'
a = np.array([1, 2, 2, 3, 4, 4, 4, 5])
b=np.unique(a,return_counts=True)
print(b)

(array([1, 2, 3, 4, 5]), array([1, 2, 1, 3, 1], dtype=int64))


In [178]:
'perform opertions: Intersection, Union, Elements in a but not in b (set difference) and Elements in either a or b but not both (symmetric difference)'
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))
print(np.setxor1d(a,b))

[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]


In [180]:
'Given an array of temperatures in Celsius, convert to Fahrenheit using a vectorized approach'
'''We've used the concept of vectorization many times in NumPy. It refers to performing element-wise operations on arrays.
array1 = np.array([1, 2, 3, 4, 5 ])
number = 10
result = array1 + number
print(result)'''
celsius = np.array([0, 20, 37, 100])
print((celsius*1.8)+32)

[ 32.   68.   98.6 212. ]


In [182]:
'Given two arrays a = np.array([1, 2, 3]), b = np.array([4, 5, 6]), stack them: Vertically and Horizontally'
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack([a,b]))
print(np.vstack([a,b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [208]:
'Create a 4x4 array with values from 0 to 15 and shuffle all rows randomly (not columns)'
a=np.arange(16).reshape(4,4)
np.random.shuffle(a)
print(a)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [209]:
'Write a function that returns "even" if a number is even, and "odd" if it is odd. Apply it to an array of numbers using np.vectorize.'
def odd_even(x):
    if x%2==0:
        return 'even'
    else:
        return 'odd'
oe=np.vectorize(odd_even)
a=np.array([1,2,3,4,5,6,7,8,9])
print(oe(a))

['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']


In [220]:
'Find the indices of NaN values and Replace all NaNs with the mean of the non-NaN values'
a = np.array([1, 2, np.nan, 4, np.nan, 6])
nan_mask = np.isnan(a)
mean_val = np.nanmean(a)  
a[nan_mask] = mean_val
print(a)

3.25
[1.   2.   3.25 4.   3.25 6.  ]


In [218]:
'Create a 2D array of shape (3,4) filled with random integers. Normalize the array column-wise (subtract mean and divide by std for each column)'
a=np.random.randint(1,20,12).reshape(3,4)
b=np.mean(a,axis=0).reshape(1,4)
c=np.std(a,axis=0).reshape(1,4)
d=np.subtract(a,b)
print(np.divide(d,c))

[[-0.70710678 -0.39223227 -0.9258201  -0.21997067]
 [-0.70710678  1.37281295  1.38873015  1.31982404]
 [ 1.41421356 -0.98058068 -0.46291005 -1.09985336]]
